// Generated by gencpp from file ros_vehicle_msgs/AbortTask.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ABORTTASK_H
#define ROS_VEHICLE_MSGS_MESSAGE_ABORTTASK_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AbortTaskRequest.h>
#include <ros_vehicle_msgs/AbortTaskResponse.h>


namespace ros_vehicle_msgs
{

struct AbortTask
{

typedef AbortTaskRequest Request;
typedef AbortTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AbortTask
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AbortTask > {
  static const char* value()
  {
    return "9e9f523ac49b499f5fdfc79efaa4ae6d";
  }

  static const char* value(const ::ros_vehicle_msgs::AbortTask&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AbortTask > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AbortTask";
  }

  static const char* value(const ::ros_vehicle_msgs::AbortTask&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AbortTaskRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AbortTask > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AbortTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AbortTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AbortTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AbortTaskRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AbortTask > 
template<>
struct DataType< ::ros_vehicle_msgs::AbortTaskRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AbortTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AbortTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AbortTaskResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AbortTask > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AbortTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AbortTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AbortTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AbortTaskResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AbortTask > 
template<>
struct DataType< ::ros_vehicle_msgs::AbortTaskResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AbortTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AbortTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ABORTTASK_H
