// Generated by gencpp from file ros_vehicle_msgs/AbortTaskRequest.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ABORTTASKREQUEST_H
#define ROS_VEHICLE_MSGS_MESSAGE_ABORTTASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vehicle_msgs
{
template <class ContainerAllocator>
struct AbortTaskRequest_
{
  typedef AbortTaskRequest_<ContainerAllocator> Type;

  AbortTaskRequest_()
    : task(0)  {
    }
  AbortTaskRequest_(const ContainerAllocator& _alloc)
    : task(0)  {
    }



   typedef uint32_t _task_type;
  _task_type task;




  typedef boost::shared_ptr< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AbortTaskRequest_

typedef ::ros_vehicle_msgs::AbortTaskRequest_<std::allocator<void> > AbortTaskRequest;

typedef boost::shared_ptr< ::ros_vehicle_msgs::AbortTaskRequest > AbortTaskRequestPtr;
typedef boost::shared_ptr< ::ros_vehicle_msgs::AbortTaskRequest const> AbortTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_vehicle_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/ros_vehicle_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'big_actor_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/big_actor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "953fc17bc6f2d9485630c092ec47d7a1";
  }

  static const char* value(const ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x953fc17bc6f2d948ULL;
  static const uint64_t static_value2 = 0x5630c092ec47d7a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vehicle_msgs/AbortTaskRequest";
  }

  static const char* value(const ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 task\n\
";
  }

  static const char* value(const ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AbortTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vehicle_msgs::AbortTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ABORTTASKREQUEST_H
