// Generated by gencpp from file ros_vehicle_msgs/AddLocation.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ADDLOCATION_H
#define ROS_VEHICLE_MSGS_MESSAGE_ADDLOCATION_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AddLocationRequest.h>
#include <ros_vehicle_msgs/AddLocationResponse.h>


namespace ros_vehicle_msgs
{

struct AddLocation
{

typedef AddLocationRequest Request;
typedef AddLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddLocation
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AddLocation > {
  static const char* value()
  {
    return "7680d9188c881e0928856c2d1f2003b3";
  }

  static const char* value(const ::ros_vehicle_msgs::AddLocation&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AddLocation > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AddLocation";
  }

  static const char* value(const ::ros_vehicle_msgs::AddLocation&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AddLocationRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AddLocation > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AddLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AddLocation >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AddLocationRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AddLocation > 
template<>
struct DataType< ::ros_vehicle_msgs::AddLocationRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AddLocation >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AddLocationResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AddLocation > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AddLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AddLocation >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AddLocationResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AddLocation > 
template<>
struct DataType< ::ros_vehicle_msgs::AddLocationResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AddLocation >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ADDLOCATION_H
