// Generated by gencpp from file ros_vehicle_msgs/AddStaticVehicle.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ADDSTATICVEHICLE_H
#define ROS_VEHICLE_MSGS_MESSAGE_ADDSTATICVEHICLE_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AddStaticVehicleRequest.h>
#include <ros_vehicle_msgs/AddStaticVehicleResponse.h>


namespace ros_vehicle_msgs
{

struct AddStaticVehicle
{

typedef AddStaticVehicleRequest Request;
typedef AddStaticVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddStaticVehicle
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AddStaticVehicle > {
  static const char* value()
  {
    return "db50de574fdbb49c79f1b80c74e44a8e";
  }

  static const char* value(const ::ros_vehicle_msgs::AddStaticVehicle&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AddStaticVehicle > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AddStaticVehicle";
  }

  static const char* value(const ::ros_vehicle_msgs::AddStaticVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AddStaticVehicleRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AddStaticVehicle > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AddStaticVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AddStaticVehicle >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddStaticVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AddStaticVehicleRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AddStaticVehicle > 
template<>
struct DataType< ::ros_vehicle_msgs::AddStaticVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AddStaticVehicle >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddStaticVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AddStaticVehicleResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AddStaticVehicle > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AddStaticVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AddStaticVehicle >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddStaticVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AddStaticVehicleResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AddStaticVehicle > 
template<>
struct DataType< ::ros_vehicle_msgs::AddStaticVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AddStaticVehicle >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddStaticVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ADDSTATICVEHICLE_H
