// Generated by gencpp from file ros_vehicle_msgs/AddTask.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ADDTASK_H
#define ROS_VEHICLE_MSGS_MESSAGE_ADDTASK_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AddTaskRequest.h>
#include <ros_vehicle_msgs/AddTaskResponse.h>


namespace ros_vehicle_msgs
{

struct AddTask
{

typedef AddTaskRequest Request;
typedef AddTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTask
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AddTask > {
  static const char* value()
  {
    return "5295bbfb15c328f29e782719ddf57d64";
  }

  static const char* value(const ::ros_vehicle_msgs::AddTask&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AddTask > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AddTask";
  }

  static const char* value(const ::ros_vehicle_msgs::AddTask&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AddTaskRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AddTask > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AddTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AddTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AddTaskRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AddTask > 
template<>
struct DataType< ::ros_vehicle_msgs::AddTaskRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AddTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AddTaskResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AddTask > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AddTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AddTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AddTaskResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AddTask > 
template<>
struct DataType< ::ros_vehicle_msgs::AddTaskResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AddTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AddTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ADDTASK_H
