// Generated by gencpp from file ros_vehicle_msgs/AddTaskRequest.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ADDTASKREQUEST_H
#define ROS_VEHICLE_MSGS_MESSAGE_ADDTASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <big_actor_msgs/Task.h>

namespace ros_vehicle_msgs
{
template <class ContainerAllocator>
struct AddTaskRequest_
{
  typedef AddTaskRequest_<ContainerAllocator> Type;

  AddTaskRequest_()
    : task()
    , update(false)  {
    }
  AddTaskRequest_(const ContainerAllocator& _alloc)
    : task(_alloc)
    , update(false)  {
    }



   typedef  ::big_actor_msgs::Task_<ContainerAllocator>  _task_type;
  _task_type task;

   typedef uint8_t _update_type;
  _update_type update;




  typedef boost::shared_ptr< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTaskRequest_

typedef ::ros_vehicle_msgs::AddTaskRequest_<std::allocator<void> > AddTaskRequest;

typedef boost::shared_ptr< ::ros_vehicle_msgs::AddTaskRequest > AddTaskRequestPtr;
typedef boost::shared_ptr< ::ros_vehicle_msgs::AddTaskRequest const> AddTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ros_vehicle_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/ros_vehicle_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'big_actor_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/big_actor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0fec23346f91793c07b860ca7e10975";
  }

  static const char* value(const ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0fec23346f91793ULL;
  static const uint64_t static_value2 = 0xc07b860ca7e10975ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vehicle_msgs/AddTaskRequest";
  }

  static const char* value(const ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "big_actor_msgs/Task task\n\
bool update\n\
\n\
================================================================================\n\
MSG: big_actor_msgs/Task\n\
uint64 taskStamp                # Last update timestamp in milliseconds since the Epoch (1970-01-01 00:00:00.000 UTC).\n\
uint32 taskId                   # Unique task id\n\
uint32 taskType                 # Type of the Task (Search, GotoWP, Track, GotoLocation )\n\
    uint8 TT_NONE=0\n\
    uint8 TT_SEARCH=1\n\
    uint8 TT_GOTO_WP=2\n\
    uint8 TT_TRACK=3\n\
    uint8 TT_GOTO_LOCATION=4\n\
    uint8 TT_RETURN_HOME=5\n\
    uint8 TT_HOLD=6				# (wait in loiter)\n\
    uint8 TT_VIDEOSTREAM=7\n\
uint8 status                    # Status of the task\n\
    uint8 TS_NONE=0\n\
    uint8 TS_TODO=1             # Created and Not Assigned \n\
    uint8 TS_IN_PROGRESS=2      # Assigned and ack by vehicle  \n\
    uint8 TS_DONE=3             # Done :)\n\
    uint8 TS_ASSIGNED=4         # Assigned by task publisher not ack'd by vehicle  \n\
    uint8 TS_CANCELED=5         # Canceled by task publisher\n\
uint64 vehicleId                # Assigned or/and ack by vehicle  \n\
uint64 creationStamp            # If later we adopt a dynamic task creation (in milliseconds since the Epoch).\n\
string parameters               # JSON parameters related with task type\n\
";
  }

  static const char* value(const ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
      stream.next(m.update);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vehicle_msgs::AddTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    s << std::endl;
    Printer< ::big_actor_msgs::Task_<ContainerAllocator> >::stream(s, indent + "  ", v.task);
    s << indent << "update: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ADDTASKREQUEST_H
