// Generated by gencpp from file ros_vehicle_msgs/AISAddFilterRequest.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_AISADDFILTERREQUEST_H
#define ROS_VEHICLE_MSGS_MESSAGE_AISADDFILTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vehicle_msgs
{
template <class ContainerAllocator>
struct AISAddFilterRequest_
{
  typedef AISAddFilterRequest_<ContainerAllocator> Type;

  AISAddFilterRequest_()
    : vehicleId(0)
    , mmsi(0)  {
    }
  AISAddFilterRequest_(const ContainerAllocator& _alloc)
    : vehicleId(0)
    , mmsi(0)  {
    }



   typedef uint64_t _vehicleId_type;
  _vehicleId_type vehicleId;

   typedef uint32_t _mmsi_type;
  _mmsi_type mmsi;




  typedef boost::shared_ptr< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AISAddFilterRequest_

typedef ::ros_vehicle_msgs::AISAddFilterRequest_<std::allocator<void> > AISAddFilterRequest;

typedef boost::shared_ptr< ::ros_vehicle_msgs::AISAddFilterRequest > AISAddFilterRequestPtr;
typedef boost::shared_ptr< ::ros_vehicle_msgs::AISAddFilterRequest const> AISAddFilterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_vehicle_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/ros_vehicle_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'big_actor_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/big_actor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a16cf56af97ff9f1577529fb5f9870d";
  }

  static const char* value(const ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a16cf56af97ff9fULL;
  static const uint64_t static_value2 = 0x1577529fb5f9870dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vehicle_msgs/AISAddFilterRequest";
  }

  static const char* value(const ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 vehicleId\n\
uint32 mmsi\n\
";
  }

  static const char* value(const ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicleId);
      stream.next(m.mmsi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AISAddFilterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vehicle_msgs::AISAddFilterRequest_<ContainerAllocator>& v)
  {
    s << indent << "vehicleId: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.vehicleId);
    s << indent << "mmsi: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mmsi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_AISADDFILTERREQUEST_H
