// Generated by gencpp from file ros_vehicle_msgs/AISOn.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_AISON_H
#define ROS_VEHICLE_MSGS_MESSAGE_AISON_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AISOnRequest.h>
#include <ros_vehicle_msgs/AISOnResponse.h>


namespace ros_vehicle_msgs
{

struct AISOn
{

typedef AISOnRequest Request;
typedef AISOnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AISOn
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AISOn > {
  static const char* value()
  {
    return "8e14b7c13560b19135298241ac557c54";
  }

  static const char* value(const ::ros_vehicle_msgs::AISOn&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AISOn > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AISOn";
  }

  static const char* value(const ::ros_vehicle_msgs::AISOn&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AISOnRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AISOn > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AISOnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AISOn >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISOnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AISOnRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AISOn > 
template<>
struct DataType< ::ros_vehicle_msgs::AISOnRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AISOn >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISOnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AISOnResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AISOn > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AISOnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AISOn >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISOnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AISOnResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AISOn > 
template<>
struct DataType< ::ros_vehicle_msgs::AISOnResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AISOn >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISOnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_AISON_H
