// Generated by gencpp from file ros_vehicle_msgs/AISOffRequest.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_AISOFFREQUEST_H
#define ROS_VEHICLE_MSGS_MESSAGE_AISOFFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vehicle_msgs
{
template <class ContainerAllocator>
struct AISOffRequest_
{
  typedef AISOffRequest_<ContainerAllocator> Type;

  AISOffRequest_()
    : vehicleId(0)  {
    }
  AISOffRequest_(const ContainerAllocator& _alloc)
    : vehicleId(0)  {
    }



   typedef uint64_t _vehicleId_type;
  _vehicleId_type vehicleId;




  typedef boost::shared_ptr< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AISOffRequest_

typedef ::ros_vehicle_msgs::AISOffRequest_<std::allocator<void> > AISOffRequest;

typedef boost::shared_ptr< ::ros_vehicle_msgs::AISOffRequest > AISOffRequestPtr;
typedef boost::shared_ptr< ::ros_vehicle_msgs::AISOffRequest const> AISOffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_vehicle_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/ros_vehicle_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'big_actor_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/big_actor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50f9f6046ca4df0f304f7522bdc4c90f";
  }

  static const char* value(const ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50f9f6046ca4df0fULL;
  static const uint64_t static_value2 = 0x304f7522bdc4c90fULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vehicle_msgs/AISOffRequest";
  }

  static const char* value(const ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 vehicleId\n\
";
  }

  static const char* value(const ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicleId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AISOffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vehicle_msgs::AISOffRequest_<ContainerAllocator>& v)
  {
    s << indent << "vehicleId: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.vehicleId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_AISOFFREQUEST_H
