// Generated by gencpp from file ros_vehicle_msgs/AISRemoveFilter.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_AISREMOVEFILTER_H
#define ROS_VEHICLE_MSGS_MESSAGE_AISREMOVEFILTER_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AISRemoveFilterRequest.h>
#include <ros_vehicle_msgs/AISRemoveFilterResponse.h>


namespace ros_vehicle_msgs
{

struct AISRemoveFilter
{

typedef AISRemoveFilterRequest Request;
typedef AISRemoveFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AISRemoveFilter
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AISRemoveFilter > {
  static const char* value()
  {
    return "574a751e9072e0c419c02c93b7c35b48";
  }

  static const char* value(const ::ros_vehicle_msgs::AISRemoveFilter&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AISRemoveFilter > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AISRemoveFilter";
  }

  static const char* value(const ::ros_vehicle_msgs::AISRemoveFilter&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AISRemoveFilterRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AISRemoveFilter > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AISRemoveFilterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AISRemoveFilter >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISRemoveFilterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AISRemoveFilterRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AISRemoveFilter > 
template<>
struct DataType< ::ros_vehicle_msgs::AISRemoveFilterRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AISRemoveFilter >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISRemoveFilterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AISRemoveFilterResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AISRemoveFilter > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AISRemoveFilterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AISRemoveFilter >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISRemoveFilterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AISRemoveFilterResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AISRemoveFilter > 
template<>
struct DataType< ::ros_vehicle_msgs::AISRemoveFilterResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AISRemoveFilter >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AISRemoveFilterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_AISREMOVEFILTER_H
