// Generated by gencpp from file ros_vehicle_msgs/AssignTask.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_ASSIGNTASK_H
#define ROS_VEHICLE_MSGS_MESSAGE_ASSIGNTASK_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/AssignTaskRequest.h>
#include <ros_vehicle_msgs/AssignTaskResponse.h>


namespace ros_vehicle_msgs
{

struct AssignTask
{

typedef AssignTaskRequest Request;
typedef AssignTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignTask
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::AssignTask > {
  static const char* value()
  {
    return "08fbfe04ba3c39af4e051274e9c94633";
  }

  static const char* value(const ::ros_vehicle_msgs::AssignTask&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::AssignTask > {
  static const char* value()
  {
    return "ros_vehicle_msgs/AssignTask";
  }

  static const char* value(const ::ros_vehicle_msgs::AssignTask&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::AssignTaskRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AssignTask > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AssignTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AssignTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AssignTaskRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AssignTask > 
template<>
struct DataType< ::ros_vehicle_msgs::AssignTaskRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AssignTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::AssignTaskResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::AssignTask > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::AssignTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::AssignTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AssignTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::AssignTaskResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::AssignTask > 
template<>
struct DataType< ::ros_vehicle_msgs::AssignTaskResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::AssignTask >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::AssignTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_ASSIGNTASK_H
