// Generated by gencpp from file ros_vehicle_msgs/GetVehicles.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_GETVEHICLES_H
#define ROS_VEHICLE_MSGS_MESSAGE_GETVEHICLES_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/GetVehiclesRequest.h>
#include <ros_vehicle_msgs/GetVehiclesResponse.h>


namespace ros_vehicle_msgs
{

struct GetVehicles
{

typedef GetVehiclesRequest Request;
typedef GetVehiclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVehicles
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::GetVehicles > {
  static const char* value()
  {
    return "fc55862084b8f5e07baaa8d8b29bc212";
  }

  static const char* value(const ::ros_vehicle_msgs::GetVehicles&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::GetVehicles > {
  static const char* value()
  {
    return "ros_vehicle_msgs/GetVehicles";
  }

  static const char* value(const ::ros_vehicle_msgs::GetVehicles&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::GetVehiclesRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::GetVehicles > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::GetVehiclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::GetVehicles >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetVehiclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::GetVehiclesRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::GetVehicles > 
template<>
struct DataType< ::ros_vehicle_msgs::GetVehiclesRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::GetVehicles >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetVehiclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::GetVehiclesResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::GetVehicles > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::GetVehiclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::GetVehicles >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetVehiclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::GetVehiclesResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::GetVehicles > 
template<>
struct DataType< ::ros_vehicle_msgs::GetVehiclesResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::GetVehicles >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetVehiclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_GETVEHICLES_H
