// Generated by gencpp from file ros_vehicle_msgs/GetWaypoints.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_GETWAYPOINTS_H
#define ROS_VEHICLE_MSGS_MESSAGE_GETWAYPOINTS_H

#include <ros/service_traits.h>


#include <ros_vehicle_msgs/GetWaypointsRequest.h>
#include <ros_vehicle_msgs/GetWaypointsResponse.h>


namespace ros_vehicle_msgs
{

struct GetWaypoints
{

typedef GetWaypointsRequest Request;
typedef GetWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypoints
} // namespace ros_vehicle_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vehicle_msgs::GetWaypoints > {
  static const char* value()
  {
    return "37560f72d0b1c9e36f8ce9a81e339b28";
  }

  static const char* value(const ::ros_vehicle_msgs::GetWaypoints&) { return value(); }
};

template<>
struct DataType< ::ros_vehicle_msgs::GetWaypoints > {
  static const char* value()
  {
    return "ros_vehicle_msgs/GetWaypoints";
  }

  static const char* value(const ::ros_vehicle_msgs::GetWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vehicle_msgs::GetWaypointsRequest> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::GetWaypoints > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::GetWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::GetWaypointsRequest> should match 
// service_traits::DataType< ::ros_vehicle_msgs::GetWaypoints > 
template<>
struct DataType< ::ros_vehicle_msgs::GetWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vehicle_msgs::GetWaypointsResponse> should match 
// service_traits::MD5Sum< ::ros_vehicle_msgs::GetWaypoints > 
template<>
struct MD5Sum< ::ros_vehicle_msgs::GetWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vehicle_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vehicle_msgs::GetWaypointsResponse> should match 
// service_traits::DataType< ::ros_vehicle_msgs::GetWaypoints > 
template<>
struct DataType< ::ros_vehicle_msgs::GetWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vehicle_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::ros_vehicle_msgs::GetWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_GETWAYPOINTS_H
