// Generated by gencpp from file ros_vehicle_msgs/ServiceReturnBool.msg
// DO NOT EDIT!


#ifndef ROS_VEHICLE_MSGS_MESSAGE_SERVICERETURNBOOL_H
#define ROS_VEHICLE_MSGS_MESSAGE_SERVICERETURNBOOL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vehicle_msgs
{
template <class ContainerAllocator>
struct ServiceReturnBool_
{
  typedef ServiceReturnBool_<ContainerAllocator> Type;

  ServiceReturnBool_()
    : ok(false)
    , error()  {
    }
  ServiceReturnBool_(const ContainerAllocator& _alloc)
    : ok(false)
    , error(_alloc)  {
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;




  typedef boost::shared_ptr< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceReturnBool_

typedef ::ros_vehicle_msgs::ServiceReturnBool_<std::allocator<void> > ServiceReturnBool;

typedef boost::shared_ptr< ::ros_vehicle_msgs::ServiceReturnBool > ServiceReturnBoolPtr;
typedef boost::shared_ptr< ::ros_vehicle_msgs::ServiceReturnBool const> ServiceReturnBoolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ros_vehicle_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/ros_vehicle_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'big_actor_msgs': ['/home/eloi/bigactorrte/ros_workspace/src/big_actor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14d6fca830116fb9833d983a296f00ed";
  }

  static const char* value(const ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14d6fca830116fb9ULL;
  static const uint64_t static_value2 = 0x833d983a296f00edULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vehicle_msgs/ServiceReturnBool";
  }

  static const char* value(const ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n\
string error\n\
";
  }

  static const char* value(const ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ServiceReturnBool_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vehicle_msgs::ServiceReturnBool_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VEHICLE_MSGS_MESSAGE_SERVICERETURNBOOL_H
