"""autogenerated by genpy from ros_vehicle_msgs/AddTaskRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import big_actor_msgs.msg

class AddTaskRequest(genpy.Message):
  _md5sum = "f0fec23346f91793c07b860ca7e10975"
  _type = "ros_vehicle_msgs/AddTaskRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """big_actor_msgs/Task task
bool update

================================================================================
MSG: big_actor_msgs/Task
uint64 taskStamp                # Last update timestamp in milliseconds since the Epoch (1970-01-01 00:00:00.000 UTC).
uint32 taskId                   # Unique task id
uint32 taskType                 # Type of the Task (Search, GotoWP, Track, GotoLocation )
    uint8 TT_NONE=0
    uint8 TT_SEARCH=1
    uint8 TT_GOTO_WP=2
    uint8 TT_TRACK=3
    uint8 TT_GOTO_LOCATION=4
    uint8 TT_RETURN_HOME=5
    uint8 TT_HOLD=6				# (wait in loiter)
    uint8 TT_VIDEOSTREAM=7
uint8 status                    # Status of the task
    uint8 TS_NONE=0
    uint8 TS_TODO=1             # Created and Not Assigned 
    uint8 TS_IN_PROGRESS=2      # Assigned and ack by vehicle  
    uint8 TS_DONE=3             # Done :)
    uint8 TS_ASSIGNED=4         # Assigned by task publisher not ack'd by vehicle  
    uint8 TS_CANCELED=5         # Canceled by task publisher
uint64 vehicleId                # Assigned or/and ack by vehicle  
uint64 creationStamp            # If later we adopt a dynamic task creation (in milliseconds since the Epoch).
string parameters               # JSON parameters related with task type
"""
  __slots__ = ['task','update']
  _slot_types = ['big_actor_msgs/Task','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task,update

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddTaskRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.task is None:
        self.task = big_actor_msgs.msg.Task()
      if self.update is None:
        self.update = False
    else:
      self.task = big_actor_msgs.msg.Task()
      self.update = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Q2IB2Q.pack(_x.task.taskStamp, _x.task.taskId, _x.task.taskType, _x.task.status, _x.task.vehicleId, _x.task.creationStamp))
      _x = self.task.parameters
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.update))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.task is None:
        self.task = big_actor_msgs.msg.Task()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.task.taskStamp, _x.task.taskId, _x.task.taskType, _x.task.status, _x.task.vehicleId, _x.task.creationStamp,) = _struct_Q2IB2Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task.parameters = str[start:end].decode('utf-8')
      else:
        self.task.parameters = str[start:end]
      start = end
      end += 1
      (self.update,) = _struct_B.unpack(str[start:end])
      self.update = bool(self.update)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Q2IB2Q.pack(_x.task.taskStamp, _x.task.taskId, _x.task.taskType, _x.task.status, _x.task.vehicleId, _x.task.creationStamp))
      _x = self.task.parameters
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.update))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.task is None:
        self.task = big_actor_msgs.msg.Task()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.task.taskStamp, _x.task.taskId, _x.task.taskType, _x.task.status, _x.task.vehicleId, _x.task.creationStamp,) = _struct_Q2IB2Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task.parameters = str[start:end].decode('utf-8')
      else:
        self.task.parameters = str[start:end]
      start = end
      end += 1
      (self.update,) = _struct_B.unpack(str[start:end])
      self.update = bool(self.update)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_Q2IB2Q = struct.Struct("<Q2IB2Q")
"""autogenerated by genpy from ros_vehicle_msgs/AddTaskResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_vehicle_msgs.msg

class AddTaskResponse(genpy.Message):
  _md5sum = "b5e8783f50e6fc581fb0ee8ecc149e7f"
  _type = "ros_vehicle_msgs/AddTaskResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ServiceReturnBool result

================================================================================
MSG: ros_vehicle_msgs/ServiceReturnBool
bool ok
string error
"""
  __slots__ = ['result']
  _slot_types = ['ros_vehicle_msgs/ServiceReturnBool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddTaskResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = ros_vehicle_msgs.msg.ServiceReturnBool()
    else:
      self.result = ros_vehicle_msgs.msg.ServiceReturnBool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.result.ok))
      _x = self.result.error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.result is None:
        self.result = ros_vehicle_msgs.msg.ServiceReturnBool()
      end = 0
      start = end
      end += 1
      (self.result.ok,) = _struct_B.unpack(str[start:end])
      self.result.ok = bool(self.result.ok)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result.error = str[start:end].decode('utf-8')
      else:
        self.result.error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.result.ok))
      _x = self.result.error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.result is None:
        self.result = ros_vehicle_msgs.msg.ServiceReturnBool()
      end = 0
      start = end
      end += 1
      (self.result.ok,) = _struct_B.unpack(str[start:end])
      self.result.ok = bool(self.result.ok)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result.error = str[start:end].decode('utf-8')
      else:
        self.result.error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
class AddTask(object):
  _type          = 'ros_vehicle_msgs/AddTask'
  _md5sum = '5295bbfb15c328f29e782719ddf57d64'
  _request_class  = AddTaskRequest
  _response_class = AddTaskResponse
