"""autogenerated by genpy from ros_vehicle_msgs/UpdateWaypointRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import big_actor_msgs.msg
import ros_vehicle_msgs.msg
import std_msgs.msg

class UpdateWaypointRequest(genpy.Message):
  _md5sum = "d0efa08778c010fd9d9a0762adb224fc"
  _type = "ros_vehicle_msgs/UpdateWaypointRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Waypoint wp

================================================================================
MSG: ros_vehicle_msgs/Waypoint
Header                      header
uint16                      waypointId
uint16                      nextWp
uint16                      previousWp
bool                        start
bool                        stop
bool                        home
big_actor_msgs/LatLngAlt    position
LoiterData                  loiter

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: big_actor_msgs/LatLngAlt
float64 latitude
float64 longitude
float64 altitude
================================================================================
MSG: ros_vehicle_msgs/LoiterData
bool active             #have loiter definition 
uint16 radius           #radius of loiter in metters  
uint16 time_sec         #time in seconds to be in loiter
uint16 times            #number of loiters to do 
bool clockwise          #go clockwise direction    

"""
  __slots__ = ['wp']
  _slot_types = ['ros_vehicle_msgs/Waypoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UpdateWaypointRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wp is None:
        self.wp = ros_vehicle_msgs.msg.Waypoint()
    else:
      self.wp = ros_vehicle_msgs.msg.Waypoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.wp.header.seq, _x.wp.header.stamp.secs, _x.wp.header.stamp.nsecs))
      _x = self.wp.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3H3B3dB3HB.pack(_x.wp.waypointId, _x.wp.nextWp, _x.wp.previousWp, _x.wp.start, _x.wp.stop, _x.wp.home, _x.wp.position.latitude, _x.wp.position.longitude, _x.wp.position.altitude, _x.wp.loiter.active, _x.wp.loiter.radius, _x.wp.loiter.time_sec, _x.wp.loiter.times, _x.wp.loiter.clockwise))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.wp is None:
        self.wp = ros_vehicle_msgs.msg.Waypoint()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.wp.header.seq, _x.wp.header.stamp.secs, _x.wp.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.wp.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.wp.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.wp.waypointId, _x.wp.nextWp, _x.wp.previousWp, _x.wp.start, _x.wp.stop, _x.wp.home, _x.wp.position.latitude, _x.wp.position.longitude, _x.wp.position.altitude, _x.wp.loiter.active, _x.wp.loiter.radius, _x.wp.loiter.time_sec, _x.wp.loiter.times, _x.wp.loiter.clockwise,) = _struct_3H3B3dB3HB.unpack(str[start:end])
      self.wp.start = bool(self.wp.start)
      self.wp.stop = bool(self.wp.stop)
      self.wp.home = bool(self.wp.home)
      self.wp.loiter.active = bool(self.wp.loiter.active)
      self.wp.loiter.clockwise = bool(self.wp.loiter.clockwise)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.wp.header.seq, _x.wp.header.stamp.secs, _x.wp.header.stamp.nsecs))
      _x = self.wp.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3H3B3dB3HB.pack(_x.wp.waypointId, _x.wp.nextWp, _x.wp.previousWp, _x.wp.start, _x.wp.stop, _x.wp.home, _x.wp.position.latitude, _x.wp.position.longitude, _x.wp.position.altitude, _x.wp.loiter.active, _x.wp.loiter.radius, _x.wp.loiter.time_sec, _x.wp.loiter.times, _x.wp.loiter.clockwise))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.wp is None:
        self.wp = ros_vehicle_msgs.msg.Waypoint()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.wp.header.seq, _x.wp.header.stamp.secs, _x.wp.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.wp.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.wp.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.wp.waypointId, _x.wp.nextWp, _x.wp.previousWp, _x.wp.start, _x.wp.stop, _x.wp.home, _x.wp.position.latitude, _x.wp.position.longitude, _x.wp.position.altitude, _x.wp.loiter.active, _x.wp.loiter.radius, _x.wp.loiter.time_sec, _x.wp.loiter.times, _x.wp.loiter.clockwise,) = _struct_3H3B3dB3HB.unpack(str[start:end])
      self.wp.start = bool(self.wp.start)
      self.wp.stop = bool(self.wp.stop)
      self.wp.home = bool(self.wp.home)
      self.wp.loiter.active = bool(self.wp.loiter.active)
      self.wp.loiter.clockwise = bool(self.wp.loiter.clockwise)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3H3B3dB3HB = struct.Struct("<3H3B3dB3HB")
"""autogenerated by genpy from ros_vehicle_msgs/UpdateWaypointResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_vehicle_msgs.msg

class UpdateWaypointResponse(genpy.Message):
  _md5sum = "b5e8783f50e6fc581fb0ee8ecc149e7f"
  _type = "ros_vehicle_msgs/UpdateWaypointResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ServiceReturnBool result

================================================================================
MSG: ros_vehicle_msgs/ServiceReturnBool
bool ok
string error
"""
  __slots__ = ['result']
  _slot_types = ['ros_vehicle_msgs/ServiceReturnBool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UpdateWaypointResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = ros_vehicle_msgs.msg.ServiceReturnBool()
    else:
      self.result = ros_vehicle_msgs.msg.ServiceReturnBool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.result.ok))
      _x = self.result.error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.result is None:
        self.result = ros_vehicle_msgs.msg.ServiceReturnBool()
      end = 0
      start = end
      end += 1
      (self.result.ok,) = _struct_B.unpack(str[start:end])
      self.result.ok = bool(self.result.ok)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result.error = str[start:end].decode('utf-8')
      else:
        self.result.error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.result.ok))
      _x = self.result.error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.result is None:
        self.result = ros_vehicle_msgs.msg.ServiceReturnBool()
      end = 0
      start = end
      end += 1
      (self.result.ok,) = _struct_B.unpack(str[start:end])
      self.result.ok = bool(self.result.ok)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result.error = str[start:end].decode('utf-8')
      else:
        self.result.error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
class UpdateWaypoint(object):
  _type          = 'ros_vehicle_msgs/UpdateWaypoint'
  _md5sum = '6198971bac65ad537719ff30fecd8b10'
  _request_class  = UpdateWaypointRequest
  _response_class = UpdateWaypointResponse
