"""autogenerated by genpy from ros_vehicle_msgs/TaskState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TaskState(genpy.Message):
  _md5sum = "1d771a872078af9c03344db2decc0965"
  _type = "ros_vehicle_msgs/TaskState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64  vehicleId
uint8   vehicleStatus
uint64  stamp
uint32  taskId
uint8   taskStatus
"""
  __slots__ = ['vehicleId','vehicleStatus','stamp','taskId','taskStatus']
  _slot_types = ['uint64','uint8','uint64','uint32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehicleId,vehicleStatus,stamp,taskId,taskStatus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TaskState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vehicleId is None:
        self.vehicleId = 0
      if self.vehicleStatus is None:
        self.vehicleStatus = 0
      if self.stamp is None:
        self.stamp = 0
      if self.taskId is None:
        self.taskId = 0
      if self.taskStatus is None:
        self.taskStatus = 0
    else:
      self.vehicleId = 0
      self.vehicleStatus = 0
      self.stamp = 0
      self.taskId = 0
      self.taskStatus = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_QBQIB.pack(_x.vehicleId, _x.vehicleStatus, _x.stamp, _x.taskId, _x.taskStatus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.vehicleId, _x.vehicleStatus, _x.stamp, _x.taskId, _x.taskStatus,) = _struct_QBQIB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_QBQIB.pack(_x.vehicleId, _x.vehicleStatus, _x.stamp, _x.taskId, _x.taskStatus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.vehicleId, _x.vehicleStatus, _x.stamp, _x.taskId, _x.taskStatus,) = _struct_QBQIB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_QBQIB = struct.Struct("<QBQIB")
