// Generated by gencpp from file piccolo_ros/PiccoloCommand.msg
// DO NOT EDIT!


#ifndef PICCOLO_ROS_MESSAGE_PICCOLOCOMMAND_H
#define PICCOLO_ROS_MESSAGE_PICCOLOCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piccolo_ros
{
template <class ContainerAllocator>
struct PiccoloCommand_
{
  typedef PiccoloCommand_<ContainerAllocator> Type;

  PiccoloCommand_()
    : header()
    , vehicleid(0)
    , command_code(0)
    , value(0.0)  {
    }
  PiccoloCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicleid(0)
    , command_code(0)
    , value(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _vehicleid_type;
  _vehicleid_type vehicleid;

   typedef int8_t _command_code_type;
  _command_code_type command_code;

   typedef float _value_type;
  _value_type value;


    enum { CC_IAS = 0u };
     enum { CC_ALTITUDE = 1u };
     enum { CC_BANK = 2u };
     enum { CC_FLAPS = 3u };
     enum { CC_HEADING = 4u };
     enum { CC_VRATE = 5u };
     enum { CC_PITCH = 6u };
 

  typedef boost::shared_ptr< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PiccoloCommand_

typedef ::piccolo_ros::PiccoloCommand_<std::allocator<void> > PiccoloCommand;

typedef boost::shared_ptr< ::piccolo_ros::PiccoloCommand > PiccoloCommandPtr;
typedef boost::shared_ptr< ::piccolo_ros::PiccoloCommand const> PiccoloCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piccolo_ros::PiccoloCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piccolo_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'piccolo_ros': ['/home/eloi/bigactorrte/ros_workspace/src/piccolo_ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a29bce3e7664a3587d1b078e48618850";
  }

  static const char* value(const ::piccolo_ros::PiccoloCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa29bce3e7664a358ULL;
  static const uint64_t static_value2 = 0x7d1b078e48618850ULL;
};

template<class ContainerAllocator>
struct DataType< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piccolo_ros/PiccoloCommand";
  }

  static const char* value(const ::piccolo_ros::PiccoloCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint16 vehicleid\n\
int8 command_code\n\
    uint8 CC_IAS=0\n\
    uint8 CC_ALTITUDE=1\n\
    uint8 CC_BANK=2\n\
    uint8 CC_FLAPS=3\n\
    uint8 CC_HEADING=4\n\
    uint8 CC_VRATE=5\n\
    uint8 CC_PITCH=6\n\
float32 value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piccolo_ros::PiccoloCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicleid);
      stream.next(m.command_code);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PiccoloCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piccolo_ros::PiccoloCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piccolo_ros::PiccoloCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicleid: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.vehicleid);
    s << indent << "command_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command_code);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICCOLO_ROS_MESSAGE_PICCOLOCOMMAND_H
