(cl:defpackage piccolo_ros-msg
  (:use )
  (:export
   "<PICCOLOSTATUS>"
   "PICCOLOSTATUS"
   "<PICCOLOWPLIST>"
   "PICCOLOWPLIST"
   "<PICCOLOTOPAYLOAD>"
   "PICCOLOTOPAYLOAD"
   "<PICCOLOREQUESTWAYPOINTS>"
   "PICCOLOREQUESTWAYPOINTS"
   "<PICCOLOTELEMETRY>"
   "PICCOLOTELEMETRY"
   "<PICCOLOWAYPOINT>"
   "PICCOLOWAYPOINT"
   "<PICCOLOCOMMAND>"
   "PICCOLOCOMMAND"
   "<PICCOLOTRACK>"
   "PICCOLOTRACK"
   "<PICCOLOFROMPAYLOAD>"
   "PICCOLOFROMPAYLOAD"
  ))

